import { IProduct, ICategory, IGalleryItem, IBusinessInfo } from './types';

export const INITIAL_BUSINESS_INFO: IBusinessInfo = {
  name: 'Mahaveer Glass & Plywood Hardware',
  storeName: 'Mahaveer Glass & Plywood Hardware',
  address: 'No. 21, Chetty Street, Old Pallavaram, Chennai - 600 117',
  phones: ['78714 57430', '78455 59880', '90804 57430', '78456 03776'],
  whatsapp: '917871457430',
  email: 'contact@mahaveerhardware.com',
  openingHours: 'Monday - Saturday: 9:00 AM - 9:00 PM | Sunday: 9:30 AM - 2:00 PM',
  description: 'Reliable products, quality hardware, premium glass, plywood and trusted service for your home, office, interior and commercial projects.'
};

export const INITIAL_CATEGORIES: ICategory[] = [
  { id: 'cat-1', name: 'Door Hardware', slug: 'door-hardware', description: 'Keels, hinges, handles, tower bolts, and door stoppers' },
  { id: 'cat-2', name: 'Locks', slug: 'locks', description: 'Rim locks, mortise locks, smart digital rim locks, and padlocks' },
  { id: 'cat-3', name: 'Tower Bolts', slug: 'tower-bolts', description: 'Stainless steel & premium brass heavy tower bolts' },
  { id: 'cat-4', name: 'Aldrops', slug: 'aldrops', description: 'Heavy-duty brass & SS aldrops for main doors and gates' },
  { id: 'cat-5', name: 'Door Stoppers', slug: 'door-stoppers', description: 'Stainless steel, antique finish, and heavy rubber stoppers' },
  { id: 'cat-6', name: 'Door Magnets', slug: 'door-magnets', description: 'Magnetic door catchers and wall mounts' },
  { id: 'cat-7', name: 'Glass Hardware', slug: 'glass-hardware', description: 'Glass fittings, spider fittings, hinges, patch fittings, and clamps' },
  { id: 'cat-8', name: 'Plywood', slug: 'plywood', description: 'Commercial plywood, marine grade, BWR/BWP, and blockboards' },
  { id: 'cat-9', name: 'Laminates', slug: 'laminates', description: 'High-pressure decorative laminates, acrylic sheets, and veneers' },
  { id: 'cat-10', name: 'Furniture Hardware', slug: 'furniture-hardware', description: 'Drawer channels, hinges, handles, knobs, and leg supports' },
  { id: 'cat-11', name: 'Kitchen Hardware', slug: 'kitchen-hardware', description: 'Modular kitchen baskets, tandem boxes, and soft-close pullouts' },
  { id: 'cat-12', name: 'Other Hardware', slug: 'other-hardware', description: 'Fasteners, screws, silicone sealants, tools, and accessories' },
];

export const INITIAL_PRODUCTS: IProduct[] = [
  // Fasteners, Adhesives & Liquid Variants
  {
    id: 'prod-adh-1',
    name: 'Fevicol Marine Wood Adhesive',
    category: 'Other Hardware',
    price: 360,
    basePrice: 420,
    discountType: 'percentage',
    discountValue: 14,
    priceDisplay: '₹360',
    shortDescription: 'Waterproof synthetic resin adhesive designed for plywood, laminates & wood joining.',
    description: 'Superior waterproofing adhesive with high bond strength for residential and commercial woodwork.',
    specifications: ['Water Resistance: Marine Grade', 'Setting Time: 4-6 Hours', 'Coverage: ~45-50 sq.ft per kg'],
    variants: ['500 gm', '1 Litre', '2 Litre', '5 Litre'],
    variantsData: [
      { id: 'var-adh-500g', name: '500 gm', basePrice: 220, sellingPrice: 190, discountType: 'percentage', discountValue: 14, inStock: true, order: 0 },
      { id: 'var-adh-1l', name: '1 Litre', basePrice: 420, sellingPrice: 360, discountType: 'percentage', discountValue: 14, inStock: true, order: 1 },
      { id: 'var-adh-2l', name: '2 Litre', basePrice: 820, sellingPrice: 690, discountType: 'percentage', discountValue: 16, inStock: true, order: 2 },
      { id: 'var-adh-5l', name: '5 Litre', basePrice: 1980, sellingPrice: 1650, discountType: 'percentage', discountValue: 17, inStock: true, order: 3 },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=600&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=600&auto=format&fit=crop&q=80',
    availability: 'In Stock',
    available: true,
    featured: true,
  },
  {
    id: 'prod-seal-1',
    name: 'Clear Silicone Glass Sealant & Adhesive',
    category: 'Glass Hardware',
    price: 240,
    basePrice: 300,
    discountType: 'percentage',
    discountValue: 20,
    priceDisplay: '₹240',
    shortDescription: 'Neutral cure 100% silicone sealant for glass partitions, window glazing and bathroom joints.',
    description: 'High-performance clear waterproof silicone sealant offering UV resistance and permanent elasticity.',
    specifications: ['Cure Type: Neutral Cure', 'Colour: Crystal Clear / Black / White', 'Temperature Resistance: -40°C to +150°C'],
    variants: ['300 ml Cartridge', '600 ml Sausage', '1 Litre Tub'],
    variantsData: [
      { id: 'var-seal-300ml', name: '300 ml Cartridge', basePrice: 300, sellingPrice: 240, discountType: 'percentage', discountValue: 20, inStock: true, order: 0 },
      { id: 'var-seal-600ml', name: '600 ml Sausage', basePrice: 560, sellingPrice: 440, discountType: 'percentage', discountValue: 21, inStock: true, order: 1 },
      { id: 'var-seal-1l', name: '1 Litre Tub', basePrice: 900, sellingPrice: 720, discountType: 'percentage', discountValue: 20, inStock: true, order: 2 },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&auto=format&fit=crop&q=80',
    availability: 'In Stock',
    available: true,
    featured: true,
  },
  // Price List Items
  {
    id: 'prod-1',
    name: '5" S.S Keel',
    category: 'Door Hardware',
    price: 110,
    basePrice: 140,
    discountType: 'percentage',
    discountValue: 21,
    priceDisplay: '₹110',
    shortDescription: 'High quality stainless steel keel fitting for durable door mounting.',
    description: 'High quality stainless steel keel fitting for durable door mounting.',
    specifications: ['Size: 5 inches', 'Material: Grade 304 Stainless Steel', 'Finish: Satin / Matte'],
    variants: ['Standard S.S (5")', 'Heavy S.S (6")'],
    variantsData: [
      { id: 'var-keel-5', name: 'Standard S.S (5")', basePrice: 140, sellingPrice: 110, discountType: 'percentage', discountValue: 21, inStock: true, order: 0 },
      { id: 'var-keel-6', name: 'Heavy S.S (6")', basePrice: 180, sellingPrice: 145, discountType: 'percentage', discountValue: 19, inStock: true, order: 1 },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&auto=format&fit=crop&q=80',
    availability: 'In Stock',
    available: true,
    featured: true,
    isPriceListItem: true
  },
  {
    id: 'prod-2',
    name: '5" Brass Keel',
    category: 'Door Hardware',
    price: 360,
    basePrice: 450,
    discountType: 'percentage',
    discountValue: 20,
    priceDisplay: '₹360',
    shortDescription: 'Premium solid brass keel for elegant traditional and modern wood doors.',
    description: 'Premium solid brass keel for elegant traditional and modern wood doors.',
    specifications: ['Size: 5 inches', 'Material: Pure Brass', 'Finish: Polished Brass / Antique'],
    variants: ['Polished Brass (5")', 'Antique Brass (5")', 'Polished Brass (6")'],
    variantsData: [
      { id: 'var-bkeel-pb5', name: 'Polished Brass (5")', basePrice: 450, sellingPrice: 360, discountType: 'percentage', discountValue: 20, inStock: true, order: 0 },
      { id: 'var-bkeel-ab5', name: 'Antique Brass (5")', basePrice: 480, sellingPrice: 380, discountType: 'percentage', discountValue: 21, inStock: true, order: 1 },
      { id: 'var-bkeel-pb6', name: 'Polished Brass (6")', basePrice: 580, sellingPrice: 460, discountType: 'percentage', discountValue: 21, inStock: true, order: 2 },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1517646287270-a5a9ca602e5c?w=600&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1517646287270-a5a9ca602e5c?w=600&auto=format&fit=crop&q=80',
    availability: 'In Stock',
    available: true,
    featured: true,
    isPriceListItem: true
  },
  {
    id: 'prod-3',
    name: '6" S.S Tower Bolt',
    category: 'Tower Bolts',
    price: 85,
    basePrice: 110,
    discountType: 'percentage',
    discountValue: 23,
    priceDisplay: '₹85',
    shortDescription: 'Rust-resistant stainless steel tower bolt with smooth slide action.',
    description: 'Rust-resistant stainless steel tower bolt with smooth slide action.',
    specifications: ['Length: 6 inches', 'Material: Stainless Steel', 'Includes mounting screws'],
    variants: ['6" S.S Standard', '8" S.S Heavy'],
    variantsData: [
      { id: 'var-tb-6ss', name: '6" S.S Standard', basePrice: 110, sellingPrice: 85, discountType: 'percentage', discountValue: 23, inStock: true, order: 0 },
      { id: 'var-tb-8ss', name: '8" S.S Heavy', basePrice: 130, sellingPrice: 98, discountType: 'percentage', discountValue: 25, inStock: true, order: 1 },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1509644851169-2acc08aa25b5?w=600&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1509644851169-2acc08aa25b5?w=600&auto=format&fit=crop&q=80',
    availability: 'In Stock',
    available: true,
    featured: true,
    isPriceListItem: true
  },
  {
    id: 'prod-4',
    name: '8" S.S Tower Bolt',
    category: 'Tower Bolts',
    price: 98,
    basePrice: 130,
    discountType: 'percentage',
    discountValue: 25,
    priceDisplay: '₹98',
    shortDescription: 'Heavy gauge 8 inch SS tower bolt ideal for main and internal doors.',
    description: 'Heavy gauge 8 inch SS tower bolt ideal for main and internal doors.',
    specifications: ['Length: 8 inches', 'Material: Stainless Steel', 'Heavy Duty Rod'],
    variants: ['8" S.S Finish'],
    variantsData: [
      { id: 'var-tb4-8ss', name: '8" S.S Finish', basePrice: 130, sellingPrice: 98, discountType: 'percentage', discountValue: 25, inStock: true, order: 0 },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1509644851169-2acc08aa25b5?w=600&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1509644851169-2acc08aa25b5?w=600&auto=format&fit=crop&q=80',
    availability: 'In Stock',
    available: true,
    featured: true,
    isPriceListItem: true
  },
  {
    id: 'prod-5',
    name: '6" T.B Brass Tower Bolt',
    category: 'Tower Bolts',
    price: 240,
    basePrice: 300,
    discountType: 'percentage',
    discountValue: 20,
    priceDisplay: '₹240',
    shortDescription: 'Solid brass tower bolt with precision pin turn lock.',
    description: 'Solid brass tower bolt with precision pin turn lock.',
    specifications: ['Length: 6 inches', 'Material: Solid Brass', 'Finish: Gold Polished'],
    variants: ['6" Brass Gold', '8" Brass Gold'],
    variantsData: [
      { id: 'var-tb-6bg', name: '6" Brass Gold', basePrice: 300, sellingPrice: 240, discountType: 'percentage', discountValue: 20, inStock: true, order: 0 },
      { id: 'var-tb-8bg', name: '8" Brass Gold', basePrice: 350, sellingPrice: 280, discountType: 'percentage', discountValue: 20, inStock: true, order: 1 },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1517646287270-a5a9ca602e5c?w=600&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1517646287270-a5a9ca602e5c?w=600&auto=format&fit=crop&q=80',
    availability: 'In Stock',
    available: true,
    featured: true,
    isPriceListItem: true
  },
  {
    id: 'prod-6',
    name: '8" T.B Brass Tower Bolt',
    category: 'Tower Bolts',
    price: 280,
    basePrice: 350,
    discountType: 'percentage',
    discountValue: 20,
    priceDisplay: '₹280',
    shortDescription: 'Heavy duty brass 8-inch tower bolt designed for extra security and aesthetics.',
    description: 'Heavy duty brass 8-inch tower bolt designed for extra security and aesthetics.',
    specifications: ['Length: 8 inches', 'Material: Solid Brass', 'Smooth Operation'],
    variants: ['Brass Gold (8")', 'Antique Brass (8")'],
    variantsData: [
      { id: 'var-tb6-8bg', name: 'Brass Gold (8")', basePrice: 350, sellingPrice: 280, discountType: 'percentage', discountValue: 20, inStock: true, order: 0 },
      { id: 'var-tb6-8ab', name: 'Antique Brass (8")', basePrice: 375, sellingPrice: 300, discountType: 'percentage', discountValue: 20, inStock: true, order: 1 },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1517646287270-a5a9ca602e5c?w=600&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1517646287270-a5a9ca602e5c?w=600&auto=format&fit=crop&q=80',
    availability: 'In Stock',
    available: true,
    featured: true,
    isPriceListItem: true
  },
  {
    id: 'prod-7',
    name: 'S.S Door Stopper',
    category: 'Door Stoppers',
    price: 75,
    basePrice: 100,
    discountType: 'percentage',
    discountValue: 25,
    priceDisplay: '₹75',
    shortDescription: 'Durable rubber tip stainless steel floor/wall door stopper.',
    description: 'Durable rubber tip stainless steel floor/wall door stopper.',
    specifications: ['Material: Stainless Steel + Rubber Buffer', 'Mount: Wall/Floor'],
    variants: ['S.S Matte', 'S.S Gloss'],
    variantsData: [
      { id: 'var-ds-ssm', name: 'S.S Matte', basePrice: 100, sellingPrice: 75, discountType: 'percentage', discountValue: 25, inStock: true, order: 0 },
      { id: 'var-ds-ssg', name: 'S.S Gloss', basePrice: 105, sellingPrice: 80, discountType: 'percentage', discountValue: 24, inStock: true, order: 1 },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&auto=format&fit=crop&q=80',
    availability: 'In Stock',
    available: true,
    featured: true,
    isPriceListItem: true
  },
  {
    id: 'prod-8',
    name: 'Ant Door Stopper',
    category: 'Door Stoppers',
    price: 290,
    basePrice: 380,
    discountType: 'percentage',
    discountValue: 24,
    priceDisplay: '₹290',
    shortDescription: 'Antique finish designer brass door stopper with heavy rubber dampener.',
    description: 'Antique finish designer brass door stopper with heavy rubber dampener.',
    specifications: ['Material: Brass alloy', 'Finish: Antique Bronze', 'Heavy load resistance'],
    variants: ['Antique Copper', 'Antique Brass'],
    variantsData: [
      { id: 'var-ds-antc', name: 'Antique Copper', basePrice: 380, sellingPrice: 290, discountType: 'percentage', discountValue: 24, inStock: true, order: 0 },
      { id: 'var-ds-antb', name: 'Antique Brass', basePrice: 390, sellingPrice: 295, discountType: 'percentage', discountValue: 24, inStock: true, order: 1 },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&auto=format&fit=crop&q=80',
    availability: 'In Stock',
    available: true,
    featured: true,
    isPriceListItem: true
  },
  {
    id: 'prod-9',
    name: 'Rim Lock',
    category: 'Locks',
    price: 3100,
    basePrice: 3800,
    discountType: 'percentage',
    discountValue: 18,
    priceDisplay: '₹3,100',
    shortDescription: 'Heavy duty dual latch rim lock for wood and iron security doors.',
    description: 'Heavy duty dual latch rim lock for wood and iron security doors.',
    specifications: ['Mechanism: Brass Pin Cylinder', 'Keys: 3 Computerised Keys', 'Finish: Dark Metallic'],
    variants: ['Standard Rim Lock (3 Keys)', 'Extended Rim Lock (5 Keys)'],
    variantsData: [
      { id: 'var-rl-std', name: 'Standard Rim Lock (3 Keys)', basePrice: 3800, sellingPrice: 3100, discountType: 'percentage', discountValue: 18, inStock: true, order: 0 },
      { id: 'var-rl-ext', name: 'Extended Rim Lock (5 Keys)', basePrice: 4200, sellingPrice: 3450, discountType: 'percentage', discountValue: 18, inStock: true, order: 1 },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=600&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=600&auto=format&fit=crop&q=80',
    availability: 'In Stock',
    available: true,
    featured: true,
    isPriceListItem: true
  },
  {
    id: 'prod-10',
    name: 'Smart Rim Lock',
    category: 'Locks',
    price: 1500,
    basePrice: 1900,
    discountType: 'percentage',
    discountValue: 21,
    priceDisplay: '₹1,500',
    shortDescription: 'Compact high-security rim lock suitable for apartment doors and cabinets.',
    description: 'Compact high-security rim lock suitable for apartment doors and cabinets.',
    specifications: ['Lock Type: Smart Rim Latch', 'Material: Zinc Alloy / Brass cylinder'],
    variants: ['S.S Chrome', 'Matte Black'],
    variantsData: [
      { id: 'var-srl-chr', name: 'S.S Chrome', basePrice: 1900, sellingPrice: 1500, discountType: 'percentage', discountValue: 21, inStock: true, order: 0 },
      { id: 'var-srl-blk', name: 'Matte Black', basePrice: 2100, sellingPrice: 1650, discountType: 'percentage', discountValue: 21, inStock: true, order: 1 },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=600&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=600&auto=format&fit=crop&q=80',
    availability: 'In Stock',
    available: true,
    featured: true,
    isPriceListItem: true
  },
  {
    id: 'prod-11',
    name: '10" S.S Aldrop',
    category: 'Aldrops',
    price: 260,
    basePrice: 340,
    discountType: 'percentage',
    discountValue: 24,
    priceDisplay: '₹260',
    shortDescription: 'Heavy gauge 10 inch stainless steel aldrop for main double doors.',
    description: 'Heavy gauge 10 inch stainless steel aldrop for main double doors.',
    specifications: ['Length: 10 inches', 'Rod Thickness: 14mm', 'Material: Stainless Steel'],
    variants: ['10" S.S Gloss', '10" S.S Matt', '12" S.S Heavy'],
    variantsData: [
      { id: 'var-ald-10g', name: '10" S.S Gloss', basePrice: 340, sellingPrice: 260, discountType: 'percentage', discountValue: 24, inStock: true, order: 0 },
      { id: 'var-ald-10m', name: '10" S.S Matt', basePrice: 360, sellingPrice: 275, discountType: 'percentage', discountValue: 24, inStock: true, order: 1 },
      { id: 'var-ald-12h', name: '12" S.S Heavy', basePrice: 420, sellingPrice: 320, discountType: 'percentage', discountValue: 24, inStock: true, order: 2 },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1509644851169-2acc08aa25b5?w=600&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1509644851169-2acc08aa25b5?w=600&auto=format&fit=crop&q=80',
    availability: 'In Stock',
    available: true,
    featured: true,
    isPriceListItem: true
  },
  {
    id: 'prod-12',
    name: '10" Brass Aldrop',
    category: 'Aldrops',
    price: 980,
    basePrice: 1250,
    discountType: 'percentage',
    discountValue: 22,
    priceDisplay: '₹980',
    shortDescription: 'Luxurious 10 inch solid brass aldrop set with decorative rosettes.',
    description: 'Luxurious 10 inch solid brass aldrop set with decorative rosettes.',
    specifications: ['Length: 10 inches', 'Material: 100% Solid Brass', 'Finish: Polished Brass / Antique'],
    variants: ['10" Polished Gold', '10" Antique Brass', '12" Heavy Gold'],
    variantsData: [
      { id: 'var-bald-10g', name: '10" Polished Gold', basePrice: 1250, sellingPrice: 980, discountType: 'percentage', discountValue: 22, inStock: true, order: 0 },
      { id: 'var-bald-10a', name: '10" Antique Brass', basePrice: 1300, sellingPrice: 1020, discountType: 'percentage', discountValue: 22, inStock: true, order: 1 },
      { id: 'var-bald-12g', name: '12" Heavy Gold', basePrice: 1600, sellingPrice: 1250, discountType: 'percentage', discountValue: 22, inStock: true, order: 2 },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1517646287270-a5a9ca602e5c?w=600&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1517646287270-a5a9ca602e5c?w=600&auto=format&fit=crop&q=80',
    availability: 'In Stock',
    available: true,
    featured: true,
    isPriceListItem: true
  },
  {
    id: 'prod-13',
    name: 'Door Magnet',
    category: 'Door Magnets',
    price: 95,
    basePrice: 130,
    discountType: 'percentage',
    discountValue: 27,
    priceDisplay: '₹95',
    shortDescription: 'Strong neodymium magnetic door catch to prevent door slamming.',
    description: 'Strong neodymium magnetic door catch to prevent door slamming.',
    specifications: ['Holding Strength: High', 'Material: SS Shell + Neodymium Magnet'],
    variants: ['Silver (Standard)', 'Bronze (Antique)'],
    variantsData: [
      { id: 'var-dm-slv', name: 'Silver (Standard)', basePrice: 130, sellingPrice: 95, discountType: 'percentage', discountValue: 27, inStock: true, order: 0 },
      { id: 'var-dm-brz', name: 'Bronze (Antique)', basePrice: 150, sellingPrice: 110, discountType: 'percentage', discountValue: 27, inStock: true, order: 1 },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&auto=format&fit=crop&q=80',
    availability: 'In Stock',
    available: true,
    featured: true,
    isPriceListItem: true
  },

  // Mortise Locks & Estimate items
  {
    id: 'prod-14',
    name: '7" Mortise Lock (KY)',
    category: 'Locks',
    price: 650,
    basePrice: 850,
    discountType: 'percentage',
    discountValue: 24,
    priceDisplay: '₹650',
    typeVariant: 'KY - Antique / S.S',
    shortDescription: '7-inch compact key operated mortise lock handle set with reversible latch.',
    description: '7-inch compact key operated mortise lock handle set with reversible latch.',
    specifications: ['Plate Size: 7 Inches', 'Type: Key (KY)', 'Finishes: Antique, S.S'],
    variants: ['7" Antique Finish', '7" S.S Finish'],
    variantsData: [
      { id: 'var-ml7-ant', name: '7" Antique Finish', basePrice: 850, sellingPrice: 650, discountType: 'percentage', discountValue: 24, inStock: true, order: 0 },
      { id: 'var-ml7-ss', name: '7" S.S Finish', basePrice: 820, sellingPrice: 620, discountType: 'percentage', discountValue: 24, inStock: true, order: 1 },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=600&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=600&auto=format&fit=crop&q=80',
    availability: 'In Stock',
    available: true,
    featured: true
  },
  {
    id: 'prod-15',
    name: '8" Mortise Lock (KY)',
    category: 'Locks',
    price: 750,
    basePrice: 980,
    discountType: 'percentage',
    discountValue: 23,
    priceDisplay: '₹750',
    typeVariant: 'KY - Antique / S.S',
    shortDescription: '8-inch standard mortise door handle with smooth mechanical double throw deadbolt.',
    description: '8-inch standard mortise door handle with smooth mechanical double throw deadbolt.',
    specifications: ['Plate Size: 8 Inches', 'Type: Key (KY)', 'Finishes: Antique, S.S'],
    variants: ['8" Antique Finish', '8" S.S Finish'],
    variantsData: [
      { id: 'var-ml8-ant', name: '8" Antique Finish', basePrice: 980, sellingPrice: 750, discountType: 'percentage', discountValue: 23, inStock: true, order: 0 },
      { id: 'var-ml8-ss', name: '8" S.S Finish', basePrice: 950, sellingPrice: 720, discountType: 'percentage', discountValue: 24, inStock: true, order: 1 },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=600&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=600&auto=format&fit=crop&q=80',
    availability: 'In Stock',
    available: true,
    featured: true
  },
  {
    id: 'prod-16',
    name: '8" Mortise Lock (CY)',
    category: 'Locks',
    price: 1800,
    basePrice: 2300,
    discountType: 'percentage',
    discountValue: 22,
    priceDisplay: '₹1,800',
    typeVariant: 'CY - Antique / S.S / Brass',
    shortDescription: '8-inch heavy Euro cylinder mortise lock with dual side key operation.',
    description: '8-inch heavy Euro cylinder mortise lock with dual side key operation.',
    specifications: ['Plate Size: 8 Inches', 'Type: Cylinder (CY)', 'Finishes: Antique, S.S, Brass'],
    variants: ['8" Antique CY', '8" S.S CY', '8" Brass Gold CY'],
    variantsData: [
      { id: 'var-ml8cy-ant', name: '8" Antique CY', basePrice: 2300, sellingPrice: 1800, discountType: 'percentage', discountValue: 22, inStock: true, order: 0 },
      { id: 'var-ml8cy-ss', name: '8" S.S CY', basePrice: 2200, sellingPrice: 1750, discountType: 'percentage', discountValue: 20, inStock: true, order: 1 },
      { id: 'var-ml8cy-bg', name: '8" Brass Gold CY', basePrice: 2500, sellingPrice: 1950, discountType: 'percentage', discountValue: 22, inStock: true, order: 2 },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=600&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=600&auto=format&fit=crop&q=80',
    availability: 'In Stock',
    available: true,
    featured: true
  },
  {
    id: 'prod-17',
    name: '10" Mortise Lock (CY)',
    category: 'Locks',
    price: 2800,
    basePrice: 3500,
    discountType: 'percentage',
    discountValue: 20,
    priceDisplay: '₹2,800',
    typeVariant: 'CY - Antique / S.S / Brass',
    shortDescription: '10-inch premium architectural mortise lock handle for luxury timber doors.',
    description: '10-inch premium architectural mortise lock handle for luxury timber doors.',
    specifications: ['Plate Size: 10 Inches', 'Type: Cylinder (CY)', 'Finishes: Antique, S.S, Brass'],
    variants: ['10" Antique CY', '10" S.S CY', '10" Brass Gold CY'],
    variantsData: [
      { id: 'var-ml10cy-ant', name: '10" Antique CY', basePrice: 3500, sellingPrice: 2800, discountType: 'percentage', discountValue: 20, inStock: true, order: 0 },
      { id: 'var-ml10cy-ss', name: '10" S.S CY', basePrice: 3400, sellingPrice: 2700, discountType: 'percentage', discountValue: 21, inStock: true, order: 1 },
      { id: 'var-ml10cy-bg', name: '10" Brass Gold CY', basePrice: 3800, sellingPrice: 3050, discountType: 'percentage', discountValue: 20, inStock: true, order: 2 },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=600&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=600&auto=format&fit=crop&q=80',
    availability: 'In Stock',
    available: true,
    featured: true
  },

  // Glass, Plywood & Kitchen Hardware items
  {
    id: 'prod-18',
    name: 'Toughened Architectural Glass (8mm - 12mm)',
    category: 'Glass Hardware',
    price: 450,
    basePrice: 560,
    discountType: 'percentage',
    discountValue: 20,
    priceDisplay: 'Starting from ₹450 / sq.ft',
    shortDescription: 'Clear and tinted safety toughened glass for partitions, doors and windows.',
    description: 'Clear and tinted safety toughened glass for partitions, doors and windows.',
    specifications: ['Thickness: 8mm, 10mm, 12mm', 'Type: Clear / Frosted / Tinted', 'Edges: Polished'],
    variants: ['8mm Clear', '10mm Clear', '12mm Clear', 'Frosted Design'],
    variantsData: [
      { id: 'var-glass-8mm', name: '8mm Clear', basePrice: 560, sellingPrice: 450, discountType: 'percentage', discountValue: 20, inStock: true, order: 0 },
      { id: 'var-glass-10mm', name: '10mm Clear', basePrice: 680, sellingPrice: 540, discountType: 'percentage', discountValue: 21, inStock: true, order: 1 },
      { id: 'var-glass-12mm', name: '12mm Clear', basePrice: 820, sellingPrice: 650, discountType: 'percentage', discountValue: 21, inStock: true, order: 2 },
      { id: 'var-glass-frosted', name: 'Frosted Design', basePrice: 750, sellingPrice: 590, discountType: 'percentage', discountValue: 21, inStock: true, order: 3 },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&auto=format&fit=crop&q=80',
    availability: 'In Stock',
    available: true
  },
  {
    id: 'prod-19',
    name: 'BWP Marine Grade Plywood (18mm)',
    category: 'Plywood',
    price: 110,
    basePrice: 140,
    discountType: 'percentage',
    discountValue: 21,
    priceDisplay: 'Starting from ₹110 / sq.ft',
    shortDescription: 'Boiling Water Proof marine plywood suitable for wardrobes, kitchens & heavy interiors.',
    description: 'Boiling Water Proof marine plywood suitable for wardrobes, kitchens & heavy interiors.',
    specifications: ['Grade: IS 710 BWP', 'Thickness: 18mm', 'Core: Gurjan / Hardwood blend'],
    variants: ['7ft x 4ft Sheet', '8ft x 4ft Sheet'],
    variantsData: [
      { id: 'var-ply-7x4', name: '7ft x 4ft Sheet (28 sq.ft)', basePrice: 3920, sellingPrice: 3080, discountType: 'percentage', discountValue: 21, inStock: true, order: 0 },
      { id: 'var-ply-8x4', name: '8ft x 4ft Sheet (32 sq.ft)', basePrice: 4480, sellingPrice: 3520, discountType: 'percentage', discountValue: 21, inStock: true, order: 1 },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1546484475-7f7bd55792da?w=600&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1546484475-7f7bd55792da?w=600&auto=format&fit=crop&q=80',
    availability: 'In Stock',
    available: true
  },
  {
    id: 'prod-20',
    name: 'High Gloss Decorative Laminate (1mm)',
    category: 'Laminates',
    price: 1350,
    basePrice: 1750,
    discountType: 'percentage',
    discountValue: 23,
    priceDisplay: '₹1,350 / sheet',
    shortDescription: 'Scratch-resistant high gloss wood grain & solid tone laminates.',
    description: 'Scratch-resistant high gloss wood grain & solid tone laminates.',
    specifications: ['Sheet Size: 8ft x 4ft', 'Thickness: 1mm', 'Finish: High Gloss / Texture'],
    variants: ['Teak Wood Texture', 'Walnut Grain', 'White High Gloss', 'Marble Look Luxury'],
    variantsData: [
      { id: 'var-lam-teak', name: 'Teak Wood Texture', basePrice: 1750, sellingPrice: 1350, discountType: 'percentage', discountValue: 23, inStock: true, order: 0 },
      { id: 'var-lam-walnut', name: 'Walnut Grain', basePrice: 1750, sellingPrice: 1350, discountType: 'percentage', discountValue: 23, inStock: true, order: 1 },
      { id: 'var-lam-wgloss', name: 'White High Gloss', basePrice: 1650, sellingPrice: 1280, discountType: 'percentage', discountValue: 22, inStock: true, order: 2 },
      { id: 'var-lam-marble', name: 'Marble Look Luxury', basePrice: 1950, sellingPrice: 1480, discountType: 'percentage', discountValue: 24, inStock: true, order: 3 },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=600&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=600&auto=format&fit=crop&q=80',
    availability: 'In Stock',
    available: true
  },
  {
    id: 'prod-21',
    name: 'Soft Close Hydraulic Hinge 3D',
    category: 'Furniture Hardware',
    price: 160,
    basePrice: 210,
    discountType: 'percentage',
    discountValue: 24,
    priceDisplay: '₹160 / pair',
    shortDescription: 'Auto-closing hydraulic cabinet hinges with 3D adjustment feature.',
    description: 'Auto-closing hydraulic cabinet hinges with 3D adjustment feature.',
    specifications: ['Type: Full Overlay / Half Overlay / Inset', 'Material: Nickel Plated Steel'],
    variants: ['Full Overlay (0 Crank)', 'Half Overlay (8 Crank)', 'Inset (16 Crank)'],
    variantsData: [
      { id: 'var-hng-fo', name: 'Full Overlay (0 Crank)', basePrice: 210, sellingPrice: 160, discountType: 'percentage', discountValue: 24, inStock: true, order: 0 },
      { id: 'var-hng-ho', name: 'Half Overlay (8 Crank)', basePrice: 210, sellingPrice: 160, discountType: 'percentage', discountValue: 24, inStock: true, order: 1 },
      { id: 'var-hng-in', name: 'Inset (16 Crank)', basePrice: 220, sellingPrice: 170, discountType: 'percentage', discountValue: 23, inStock: true, order: 2 },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&auto=format&fit=crop&q=80',
    availability: 'In Stock',
    available: true
  },
  {
    id: 'prod-22',
    name: 'Tandem Box Modular Kitchen Drawer',
    category: 'Kitchen Hardware',
    price: 2400,
    basePrice: 3100,
    discountType: 'percentage',
    discountValue: 23,
    priceDisplay: '₹2,400',
    shortDescription: 'Smooth full-extension soft-close kitchen tandem drawer system.',
    description: 'Smooth full-extension soft-close kitchen tandem drawer system.',
    specifications: ['Load Capacity: 45 KG', 'Depth: 500mm', 'Finish: Metallic Grey / White'],
    variants: ['Low Height (84mm)', 'Medium Height (135mm)', 'High Rail (199mm)'],
    variantsData: [
      { id: 'var-tdm-low', name: 'Low Height (84mm)', basePrice: 3100, sellingPrice: 2400, discountType: 'percentage', discountValue: 23, inStock: true, order: 0 },
      { id: 'var-tdm-med', name: 'Medium Height (135mm)', basePrice: 3500, sellingPrice: 2700, discountType: 'percentage', discountValue: 23, inStock: true, order: 1 },
      { id: 'var-tdm-high', name: 'High Rail (199mm)', basePrice: 3900, sellingPrice: 3050, discountType: 'percentage', discountValue: 22, inStock: true, order: 2 },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=600&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=600&auto=format&fit=crop&q=80',
    availability: 'In Stock',
    available: true
  }
];

export const INITIAL_GALLERY: IGalleryItem[] = [
  {
    id: 'gal-1',
    title: 'Mahaveer Store Showroom Front',
    category: 'Store',
    imageUrl: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800&auto=format&fit=crop&q=80',
    date: '2026-01-15'
  },
  {
    id: 'gal-2',
    title: 'Brass & SS Door Handles Display',
    category: 'Hardware',
    imageUrl: 'https://images.unsplash.com/photo-1517646287270-a5a9ca602e5c?w=800&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1517646287270-a5a9ca602e5c?w=800&auto=format&fit=crop&q=80',
    date: '2026-01-20'
  },
  {
    id: 'gal-3',
    title: 'Toughened Glass Installation Project',
    category: 'Glass Work',
    imageUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&auto=format&fit=crop&q=80',
    date: '2026-02-02'
  },
  {
    id: 'gal-4',
    title: 'BWP Marine Plywood Stock',
    category: 'Plywood',
    imageUrl: 'https://images.unsplash.com/photo-1546484475-7f7bd55792da?w=800&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1546484475-7f7bd55792da?w=800&auto=format&fit=crop&q=80',
    date: '2026-02-10'
  },
  {
    id: 'gal-5',
    title: 'Mortise & Digital Locks Display',
    category: 'Products',
    imageUrl: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80',
    date: '2026-02-15'
  },
  {
    id: 'gal-6',
    title: 'Modular Kitchen Hardware Fittings',
    category: 'Projects',
    imageUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&auto=format&fit=crop&q=80',
    date: '2026-02-18'
  }
];
